name: Build Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra

      - name: Generate PDFs
        run: |
          mkdir -p docs/GitHub-Action
          pandoc README.md -o docs/GitHub-Action/README.pdf --pdf-engine=pdflatex
          pandoc DEPLOY_RENDER.md -o docs/GitHub-Action/DEPLOY_RENDER.pdf --pdf-engine=pdflatex
          pandoc ENV_LOCAL_CONFIGURATION.md -o docs/GitHub-Action/ENV_LOCAL_CONFIGURATION.pdf --pdf-engine=pdflatex
          pandoc GUIA_LOCALHOST.md -o docs/GitHub-Action/GUIA_LOCALHOST.pdf --pdf-engine=pdflatex
          pandoc RENDER.md -o docs/GitHub-Action/RENDER.pdf --pdf-engine=pdflatex
          pandoc Guia_de_preparacion_de_docker.md -o docs/GitHub-Action/Guia_de_preparacion_de_docker.pdf --pdf-engine=pdflatex

      - name: Push changes
        run: |
          git add docs/GitHub-Action/
          git commit -m "docs: Actualizar documentaci√≥n 
          git push
