name: Build Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Markdown files to HTML/PDF in Github Action folder
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: ./docs/GitHub-Action
          output_dir: documentacion
          build_pdf: true
          build_html: true
      
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentacion
          path: docs/GitHub-Action/documentacion
          retention-days: 30

      - name: Commit and push documentation
        
      - name: Commit and push
        run: |
          git add "docs/generated-docs/"
          git commit -m "Actualizando la Documentacion"
          git push
